up = "W"
left = "A"
down = "S"
right = "D"
clockwise = "E"
anticlockwise = "Q"
aim_assist = "Space"
cycle_fullscreen = "F"

quit = "Escape"
net_mode = "Server"
addr = "192.168.1.24:20540"
grab_cursor = true