use_controller = true
up = "W"
left = "A"
down = "S"
right = "D"
clockwise = "E"
anticlockwise = "Q"
aim_assist = "Space"
cycle_fullscreen = "F"

quit = "Escape"
net_mode = "Solo"
addr = "127.0.0.1:8888"
grab_cursor = false